-- AlterTable
ALTER TABLE `driverprofile` ADD COLUMN `currentLat` DOUBLE NULL,
    ADD COLUMN `currentLng` DOUBLE NULL,
    ADD COLUMN `locationUpdatedAt` DATETIME(3) NULL;

-- AlterTable
ALTER TABLE `ride` MODIFY `status` ENUM('REQUESTED', 'ASSIGNED', 'ACCEPTED', 'DRIVER_ARRIVING', 'IN_PROGRESS', 'COMPLETED', 'CANCELED') NOT NULL DEFAULT 'REQUESTED';
